baseurl      = "https://blog.z3r0d4y.dev"
title        = "d0cuments"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

# Misc. config
enableGitInfo = true

[params]
  dateform        = "2006-01-02"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # For git commit links
  gitUrl = "https://github.com/klercke/blog.z3r0d4y.dev/commit/"

  # Subtitle for home
  homeSubtitle = "d0c_z3r0d4y's blog/documentation site"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Enable theme toggling
  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "d0cuments: d0c_z3r0d4y's blog"
  keywords = "blog, documentation, homelab, tech, linux"
  images = [""]

  # Plausible.io analytics
  plausibleDataDomain = 'blog.z3r0d4y.dev'
  plausibleScriptSource = 'https://blog.z3r0d4y.dev/js/script.js'

  # Utteranc.es (comments)
  [params.utterances]
    # Comments repo
    repository = "https://github.com/klercke/blog.z3r0d4y.dev"
    
    # Comments issue label
    label      = "Comment"

    #   Blog Post <-> Issue mapping. This parameter is optional. Possible values are:
    #      - pathname
    #      - url
    #      - title
    #      - og:title
    #      - issue number
    #      - specific term
    issueTerm  = "pathname"

    #   Theme used: possible values are:
    #      - github-light
    #      - github-dark
    #      - preferred-color-scheme
    #      - github-dark-orange
    #      - icy-dark
    #      - dark-blue
    #      - photon-dark
    #      - boxy-light
    #      - gruvbox-dark
    #
    theme      = "preferred-color-scheme"

  # Social Icons
  [[params.social]]
    name = "email"
    url = "mailto:site-contact@z3r0d4y.dev"
  
  [[params.social]]
    name = "github"
    url = "https://github.com/klercke/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/d0c_z3r0d4y/"

  [[params.social]]
    name = "gpg"
    url = "https://z3r0d4y.dev/pgp-key.txt"

[taxonomies]
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "d0cuments"
    #copyright = 'Konnor Klercke'

  [languages.en.params]
    subtitle  = "d0c's blog/documenation platform"
    readOtherPosts = "Read other posts"
    keywords = ""

    [languages.en.params.logo]
      logoText = "d0cuments"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags"

  [[menu.main]]
    identifier = "series"
    name       = "Series"
    url        = "/series"

