baseURL = "https://blog.z3r0d4y.dev/"
defaultContentLanguage = "en"
languageCode = "en"

title = "d0cuments"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

pygmentsStyle = "nord"

[menu]
  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='file-text'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
    pre = "<span data-feather='tag'></span>"
    
[params]
  # URL for the avatar on homepage
  avatarURL = "/images/logo.png"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-m"

  # Description to display on homepage
  description = "d0c's docs"

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#88C0D0"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # You can use this to inject any HTML in the <head> tag.
  # Ideal usecase for this is to import custom js/css or add your analytics snippet
  customHeadHTML = ""

  # Keywords relevant for SEO
  metaKeywords = ["blog", "tech", "programming", "linux", "raspberry", "pi"]

  # If you want to display posts on the homepage, the options are
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Footer text
  footer = "Konnor Klercke"

	dateFormat = "2006-01-02"

	socialIcons = [
		{name = "x", url = "https://x.com/d0c_z3r0d4y"},
		{name = "github", url = "https://github.com/klercke"},
		{name = "email", url = "mailto:site-contact@z3r0d4y.dev"},
		{name = "rss", url = "https://blog.z3r0d4y.dev/index.xml"},
	]

[markup]
	[markup.tableOfContents]
    startLevel = 1
	  endLevel = 3
   	ordered = false

